// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // if (kIsWeb) {
    //   return web;
    // }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        // return macos;
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for MacOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // static const FirebaseOptions web = FirebaseOptions(
  //   apiKey: '',
  //   appId: '',
  //   messagingSenderId: '',
  //   projectId: 'maverick-backend',
  //   authDomain: '',
  // storageBucket: ',
  // );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuxNpniuYO1ZvH3NHmc1IoB__5gHzgL1k',
    appId: '1:893496912353:android:12cd428dc0146f21d9caa0',
    messagingSenderId: '191792960483',
    projectId: 'maverick-backend',
    storageBucket: 'maverick-backend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuxNpniuYO1ZvH3NHmc1IoB__5gHzgL1k',
    appId: '1:191792960483:ios:2260c9f14b979366b946d6',
    messagingSenderId: '191792960483',
    projectId: 'maverick-backend',
    storageBucket: 'fir-tutorial-36108.appspot.com',
    iosBundleId: 'com.example.frontend',
  );

  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: '',
  //   appId: '',
  //   messagingSenderId: '',
  //   projectId: 'maverick-backend',
  //   storageBucket: '',
  //   iosBundleId: 'com.example.frontend',
  // );
}
